#version 430

layout (local_size_x = 30,
        local_size_z = 30) in;

struct Voxel
{
    vec4 velocity;
    vec4 staggeredVelocity;
    vec4 newStaggeredVelocity;
};

layout(binding = 2) buffer voxelsBlock
{
    Voxel voxels[];
};

void main()
{
    uint index = (gl_GlobalInvocationID.y*30*30) + (gl_GlobalInvocationID.z*30) + gl_GlobalInvocationID.x;
    voxels[index].velocity = vec4(0.0); 
    voxels[index].staggeredVelocity = vec4(0.0);
    voxels[index].newStaggeredVelocity = vec4(0.0);
}