#version 430

layout (local_size_x = 1024) in;

struct Particle
{
    vec4 position;
    vec4 velocity;
};

layout(binding = 1) buffer particlesBlock
{
    Particle particles[];
};

void main()
{
    uint index = gl_GlobalInvocationID.x;
    vec3 v = particles[index].velocity.xyz;
    vec3 p = particles[index].position.xyz;
    
    
    if(p.y > 0){
        v += (1.0/60.0) * vec3(0, -9.81, 0);
    }
   
    particles[index].velocity = vec4(v, 1.0);

}